
# config.py

WINDOW_TITLE = "Metin1"

MAP_W, MAP_H = 255, 255

MOVE_STEP_DEFAULT = 1      # 1~5 (실행 중 step 명령으로 변경 가능)
MOVE_PIXEL_PER_TILE = 32   # 타일 1칸당 클릭 픽셀 이동량(게임에 맞게 조정)

NEAR_RADIUS = 3
TICK = 0.12

# 우측상단 좌표 영역(게임창 기준 상대좌표) (x, y, w, h)
COORD_REGION_REL = (1500, 30, 220, 60)

COORD_BIN_THRESH = 160
DIGIT_MATCH_THRESH = 0.55

MOVE_CHECK_TIMEOUT = 1.2
MOVE_CHECK_POLL = 0.10

FORBIDDEN_POINTS = [
    # (10, 10),
]
FORBIDDEN_PAD = 2
FORBIDDEN_USE_CHEBYSHEV = True

TH_CHAR = 0.75
TH_MONSTER = 0.78
TH_SPECIAL = 0.85

DEBUG_SAVE_FAIL_COORD = True
DEBUG_DIR = "debug"
